import { getSettings, BLOCKED_BOT_NAMES } from './_utils';

// Served at /robots.txt via the redirect in netlify.toml, so the "Block AI
// bots" toggle in Settings can turn crawler rules on/off without a redeploy.
export default async function handler() {
    const settings = await getSettings();

    const lines = ['User-agent: *', 'Allow: /'];

    if (settings.blockAiBots) {
        lines.push('');
        for (const bot of BLOCKED_BOT_NAMES) {
            lines.push(`User-agent: ${bot}`, 'Disallow: /');
        }
    }

    lines.push('', `# Generated by Art Gallery - blockAiBots: ${settings.blockAiBots}`);

    return new Response(lines.join('\n'), {
        headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'public, max-age=300' },
    });
}
